/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GadisIdhani
 */
import java.io.UTFDataFormatException;
import java.nio.charset.Charset;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {
    

    /**
     * Creates new form Main
     */
    private static final Charset UTF8_CHARSET = Charset.forName("UTF-8");

    String p1 = "";
    String p2 = "";
    String k1 = "";
    String k2 = "";
    String c1 = "";
    String c2 = "";
    
    byte[] enc1;
    byte[] enc2;
    byte[] dec; 
    
    public static String bytesToHex(byte[] in){
        final StringBuilder builder = new StringBuilder();
        for(byte b : in){
            builder.append(String.format("%02x", b, 16));
        }
        return builder.toString();
    }
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtplain = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcipher = new javax.swing.JTextArea();
        btnenkrip1 = new javax.swing.JButton();
        btndekrip1 = new javax.swing.JButton();
        btnreset1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtwe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtkunci = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtwd = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtp1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtp2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtk1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtk2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtc1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtc2 = new javax.swing.JTextArea();
        btnenkrip2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtavalanche = new javax.swing.JTextField();
        btnreset3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtplaintext = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtkey = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtciphertext = new javax.swing.JTextArea();
        btnenkrip3 = new javax.swing.JButton();
        btndekrip2 = new javax.swing.JButton();
        txtreset2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtwenkrip = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtwdekrip = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtplain1 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtplain2 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        txtkunci1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtkunci2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtcipher1 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtcipher2 = new javax.swing.JTextArea();
        btnenkrip4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtnilaiava = new javax.swing.JTextField();
        btnreset4 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALGORITMA AES & ALGORITMA RC6");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Masukan Plaintext :");

        txtplain.setColumns(20);
        txtplain.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtplain.setRows(5);
        jScrollPane1.setViewportView(txtplain);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Masukan Kunci :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Hasil Ciphertext :");

        txtcipher.setColumns(20);
        txtcipher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcipher.setRows(5);
        jScrollPane2.setViewportView(txtcipher);

        btnenkrip1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnenkrip1.setText("ENKRIPSI");
        btnenkrip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenkrip1ActionPerformed(evt);
            }
        });

        btndekrip1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btndekrip1.setText("DEKRIPSI");
        btndekrip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndekrip1ActionPerformed(evt);
            }
        });

        btnreset1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnreset1.setText("RESET");
        btnreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Waktu Enkripsi :");

        txtwe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setText("milisecond");

        txtkunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkunciActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Waktu Dekripsi :");

        txtwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwdActionPerformed(evt);
            }
        });

        jLabel26.setText("milisecond");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtkunci, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnenkrip1)
                        .addGap(43, 43, 43)
                        .addComponent(btndekrip1)
                        .addGap(43, 43, 43)
                        .addComponent(btnreset1))
                    .addComponent(jLabel25)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtwd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtwe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel26))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnenkrip1)
                            .addComponent(btndekrip1)
                            .addComponent(btnreset1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtwe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enkripsi AES", jPanel1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Plaintext 1 :");

        txtp1.setColumns(20);
        txtp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtp1.setRows(5);
        jScrollPane3.setViewportView(txtp1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Plaintext 2 :");

        txtp2.setColumns(20);
        txtp2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtp2.setRows(5);
        jScrollPane4.setViewportView(txtp2);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Kunci 1 :");

        txtk1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtk1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Kunci 2 :");

        txtk2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Ciphertext 1 :");

        txtc1.setColumns(20);
        txtc1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtc1.setRows(5);
        jScrollPane5.setViewportView(txtc1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Ciphertext 2 :");

        txtc2.setColumns(20);
        txtc2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtc2.setRows(5);
        jScrollPane6.setViewportView(txtc2);

        btnenkrip2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnenkrip2.setText("ENKRIPSI");
        btnenkrip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenkrip2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Nilai Avalanche Effect :");

        txtavalanche.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnreset3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnreset3.setText("RESET");
        btnreset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtk1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel10))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtk2)
                            .addComponent(jScrollPane6))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnenkrip2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnreset3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel12)
                    .addComponent(txtavalanche, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnenkrip2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnreset3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtavalanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Avalanche Effect AES", jPanel2);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Plaintext :");

        txtplaintext.setColumns(20);
        txtplaintext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtplaintext.setRows(5);
        jScrollPane7.setViewportView(txtplaintext);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Kunci :");

        txtkey.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Ciphertext :");

        txtciphertext.setColumns(20);
        txtciphertext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtciphertext.setRows(5);
        jScrollPane8.setViewportView(txtciphertext);

        btnenkrip3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnenkrip3.setText("ENKRIPSI");
        btnenkrip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenkrip3ActionPerformed(evt);
            }
        });

        btndekrip2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btndekrip2.setText("DEKRIPSI");
        btndekrip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndekrip2ActionPerformed(evt);
            }
        });

        txtreset2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtreset2.setText("RESET");
        txtreset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreset2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Waktu Proses :");

        txtwenkrip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel17.setText("milisecond");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Waktu Dekripsi :");

        jLabel28.setText("milisecond");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(txtkey)
                        .addComponent(jScrollPane8))
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnenkrip3)
                        .addGap(54, 54, 54)
                        .addComponent(btndekrip2)
                        .addGap(54, 54, 54)
                        .addComponent(txtreset2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtwenkrip)
                                .addGap(4, 4, 4)))
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtwdekrip, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnenkrip3)
                            .addComponent(btndekrip2)
                            .addComponent(txtreset2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtwenkrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtwdekrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enkripsi RC6", jPanel3);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Plaintext 1 :");

        txtplain1.setColumns(20);
        txtplain1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtplain1.setRows(5);
        jScrollPane9.setViewportView(txtplain1);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Plaintext 2 :");

        txtplain2.setColumns(20);
        txtplain2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtplain2.setRows(5);
        jScrollPane10.setViewportView(txtplain2);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Kunci 1 :");

        txtkunci1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Kunci 2 :");

        txtkunci2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Ciphertext 1 :");

        txtcipher1.setColumns(20);
        txtcipher1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcipher1.setRows(5);
        jScrollPane11.setViewportView(txtcipher1);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Ciphertext 2 :");

        txtcipher2.setColumns(20);
        txtcipher2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcipher2.setRows(5);
        jScrollPane12.setViewportView(txtcipher2);

        btnenkrip4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnenkrip4.setText("ENKRIPSI");
        btnenkrip4.setToolTipText("");
        btnenkrip4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenkrip4ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Nilai Avalanche Effect :");

        txtnilaiava.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnreset4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnreset4.setText("RESET");
        btnreset4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtkunci1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                    .addComponent(jLabel20)))
                            .addComponent(jLabel22))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtkunci2)
                            .addComponent(jScrollPane12))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnenkrip4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnreset4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel24)
                    .addComponent(txtnilaiava, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnenkrip4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnreset4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkunci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkunci2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnilaiava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Avalanche Effect RC6", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnenkrip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenkrip1ActionPerformed
        // TODO add your handling code here:
        if(txtplain.getText().equals("") && txtkunci.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Plaintext dan Kunci");
        }
        else if(txtplain.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Plaintext");
        }else if(txtkunci.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Kunci");
        }
        else{
            try{
                long start = System.nanoTime();
                p1 = txtplain.getText();
                k1 = txtkunci.getText();
                enc1 = AES.encrypt(p1.getBytes(), k1.getBytes());
                String enkrip = ""+ new String(enc1);
               
                txtplain.setText("");
                txtkunci.setText("");
                
                String cipherteks = bytesToHex(enc1);
                txtcipher.setText(cipherteks);
                
                long finish = System.nanoTime();
                double wenkrip = (finish-start)/1e6;
                DecimalFormat waktu = new DecimalFormat("##0.000");
                String durasi = waktu.format(wenkrip);
                txtwe.setText(durasi);
            }catch(Exception e){
                e.printStackTrace();
            }       
        }
    }//GEN-LAST:event_btnenkrip1ActionPerformed

    private void btndekrip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndekrip1ActionPerformed
        // TODO add your handling code here:else if(txtkunci.getText().equals("")){
        if(txtkunci.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Kunci");
        }
        else{
           try{
               long start = System.nanoTime();
               c1 = txtcipher.getText();
               k1 = txtkunci.getText();
               dec = AES.decrypt(enc1 , k1.getBytes());
               String dekrip = ""+ new String(dec);
               txtplain.setText(dekrip);
               txtcipher.setText("");
               txtkunci.setText("");
            
               long finish = System.nanoTime();
               double wdekrip = (finish-start)/1e6;
               DecimalFormat waktu = new DecimalFormat("##0.000");
               String durasi = waktu.format(wdekrip);
               txtwd.setText(durasi);
            }catch(Exception e){
               e.printStackTrace();
            }  
        }
    }//GEN-LAST:event_btndekrip1ActionPerformed

    private void btnreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset1ActionPerformed
        // TODO add your handling code here:
        txtplain.setText("");
        txtkunci.setText("");
        txtcipher.setText("");
        txtwe.setText("");
        txtwd.setText("");
    }//GEN-LAST:event_btnreset1ActionPerformed

    private void txtk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtk1ActionPerformed

    private void btnenkrip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenkrip2ActionPerformed
        // TODO add your handling code here:
        if(txtp1.getText().equals("") && txtk1.getText().equals("") && txtp2.getText().equals("") && txtk2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Plaintext dan Kunci");
        }
        else if(txtp1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Plaintext ke-1");
        }
        else if(txtk1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Kunci ke-1");
        }
        else if(txtp2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Plaintext ke-2");
        }
        else if(txtk2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Kunci ke-2");
        }
        else{
        try{            
            p1= txtp1.getText();
            p2= txtp2.getText();
            k1 = txtk1.getText();
            k2 = txtk2.getText();
            enc1 = AES.encrypt(p1.getBytes(), k1.getBytes());
            enc2 = AES.encrypt(p2.getBytes(), k2.getBytes());
            String enkrip1 = ""+ new String(enc1);
            String enkrip2 = ""+ new String(enc2);
            
            String cipher1 = bytesToHex(enc1);
            String cipher2 = bytesToHex(enc2);
            
            txtc1.setText(cipher1);
            txtc2.setText(cipher2);
            
            String bit1 = enkrip1;
            String bit2 = enkrip2;
            Avalanche ava = new Avalanche();
            Double nilaiava = ava.avalanche(bit1,bit2);
            DecimalFormat avc = new DecimalFormat("##0.000");
            txtavalanche.setText(String.valueOf(avc.format(nilaiava)) +"%");
        }catch(Exception e){
            e.printStackTrace();
	}
        
        }
    }//GEN-LAST:event_btnenkrip2ActionPerformed

    private void btnenkrip3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenkrip3ActionPerformed
        // TODO add your handling code here:
        if(txtplaintext.getText().equals("") && txtkey.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Plaintext dan Kunci");
        }
        else if(txtplaintext.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Plaintext");
        }else if(txtkey.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Kunci");
        }
        else{
            try{
                long start = System.nanoTime();
                p1 = txtplaintext.getText();
                k1 = txtkey.getText();
                enc1 = RC6.encrypt(p1.getBytes(), k1.getBytes());
                String enkrip = ""+ new String(enc1);
                String cipherteks = bytesToHex(enc1);
                txtciphertext.setText(cipherteks);
                long finish = System.nanoTime();
                double wenkrip = (finish-start)/1e6;
                DecimalFormat waktu = new DecimalFormat("##0.000");
                String durasi = waktu.format(wenkrip);
                txtwenkrip.setText(durasi);
               }
                catch(Exception e){
                    e.printStackTrace();
                }
                txtplaintext.setText("");
                txtkey.setText("");
        }
    }//GEN-LAST:event_btnenkrip3ActionPerformed

    private void btndekrip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndekrip2ActionPerformed
        // TODO add your handling code here:
        if(txtkey.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum memasukan Kunci");
        }
        else{
            try{
                long start = System.nanoTime();
                c1 = txtciphertext.getText();
                k1 = txtkey.getText();           
                dec = RC6.decrypt(enc1, k1.getBytes());
                String dekrip = ""+ new String(dec);
                txtplaintext.setText(dekrip);
                txtciphertext.setText("");
                txtkey.setText("");
                long finish = System.nanoTime();
                double wdekrip = (finish-start)/1e6;
                DecimalFormat waktu = new DecimalFormat("##0.000");
                String durasi = waktu.format(wdekrip);
                txtwdekrip.setText(durasi);
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btndekrip2ActionPerformed

    private void txtreset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreset2ActionPerformed
        // TODO add your handling code here:
        txtplaintext.setText("");
        txtkey.setText("");
        txtciphertext.setText("");
        txtwenkrip.setText("");
        txtwdekrip.setText("");
    }//GEN-LAST:event_txtreset2ActionPerformed

    private void btnenkrip4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenkrip4ActionPerformed
        // TODO add your handling code here:
        try{
            p1 = txtplain1.getText();
            p2 = txtplain2.getText();
            k1 = txtkunci1.getText();
            k2 = txtkunci2.getText();
            enc1 = RC6.encrypt(p1.getBytes(), k1.getBytes());
            enc2 = RC6.encrypt(p2.getBytes(), k2.getBytes());
            String enkrip1 = ""+ new String(enc1);
            String enkrip2 = ""+ new String(enc2);
            
            String ciphertext1 = bytesToHex(enc1);
            String ciphertext2 = bytesToHex(enc2);
            txtcipher1.setText(ciphertext1);
            txtcipher2.setText(ciphertext2);
            
            String bit1 = enkrip1;
            String bit2 = enkrip2;
            Avalanche ava = new Avalanche();
            Double nilaiava = ava.avalanche(bit1,bit2);
            DecimalFormat avc = new DecimalFormat("##0.000");
            txtnilaiava.setText(String.valueOf(avc.format(nilaiava)) +"%");
        }
        catch(Exception e){
            e.printStackTrace();
	}
        
        
    }//GEN-LAST:event_btnenkrip4ActionPerformed

    private void txtkunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkunciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkunciActionPerformed

    private void btnreset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset3ActionPerformed
        // TODO add your handling code here:
        txtp1.setText("");
        txtp2.setText("");
        txtk1.setText("");
        txtk2.setText("");
        txtc1.setText("");
        txtc2.setText("");
        txtavalanche.setText("");
    }//GEN-LAST:event_btnreset3ActionPerformed

    private void btnreset4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset4ActionPerformed
        // TODO add your handling code here:
        txtplain1.setText("");
        txtplain2.setText("");
        txtkunci1.setText("");
        txtkunci2.setText("");
        txtcipher1.setText("");
        txtcipher2.setText("");
        txtnilaiava.setText("");
    }//GEN-LAST:event_btnreset4ActionPerformed

    private void txtwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndekrip1;
    private javax.swing.JButton btndekrip2;
    private javax.swing.JButton btnenkrip1;
    private javax.swing.JButton btnenkrip2;
    private javax.swing.JButton btnenkrip3;
    private javax.swing.JButton btnenkrip4;
    private javax.swing.JButton btnreset1;
    private javax.swing.JButton btnreset3;
    private javax.swing.JButton btnreset4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtavalanche;
    private javax.swing.JTextArea txtc1;
    private javax.swing.JTextArea txtc2;
    private javax.swing.JTextArea txtcipher;
    private javax.swing.JTextArea txtcipher1;
    private javax.swing.JTextArea txtcipher2;
    private javax.swing.JTextArea txtciphertext;
    private javax.swing.JTextField txtk1;
    private javax.swing.JTextField txtk2;
    private javax.swing.JTextField txtkey;
    private javax.swing.JTextField txtkunci;
    private javax.swing.JTextField txtkunci1;
    private javax.swing.JTextField txtkunci2;
    private javax.swing.JTextField txtnilaiava;
    private javax.swing.JTextArea txtp1;
    private javax.swing.JTextArea txtp2;
    private javax.swing.JTextArea txtplain;
    private javax.swing.JTextArea txtplain1;
    private javax.swing.JTextArea txtplain2;
    private javax.swing.JTextArea txtplaintext;
    private javax.swing.JButton txtreset2;
    private javax.swing.JTextField txtwd;
    private javax.swing.JTextField txtwdekrip;
    private javax.swing.JTextField txtwe;
    private javax.swing.JTextField txtwenkrip;
    // End of variables declaration//GEN-END:variables
}
